name: SeaBASS-PRISM

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Extras
        id: cache-extras
        uses: actions/cache@v5
        with:
          path: ~/.isofit
          key: extras-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: "3.12"
          activate-environment: true

      - name: Install ISOFIT
        run: |
          uv pip install "isofit[plots] @ git+https://github.com/isofit/isofit@dev"

      - name: Execute tests
        run: |
          mkdir results

          RUN=$(isofit path examples)/SeaBASS_prism_001/
          $RUN/default.sh --log_file results/default.log --resources

          isoplots spfit -p $RUN -o results/default.png
          isoplots resources results/default.resources.jsonl -o results/default.resources.html -l results/default.log --relative --png --debug

      - uses: actions/upload-artifact@v6
        with:
          name: SeaBASS_prism_001
          path: results
